/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NaranjaCustomerApiTesting);
  }
}(this, function(expect, NaranjaCustomerApiTesting) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Customerscustomeridcontactdetailsaddressescategoryidaddresses', function() {
    it('should create an instance of Customerscustomeridcontactdetailsaddressescategoryidaddresses', function() {
      // uncomment below and update the code to test Customerscustomeridcontactdetailsaddressescategoryidaddresses
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be.a(NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses);
    });

    it('should have the property streetName (base name: "street_name")', function() {
      // uncomment below and update the code to test the property streetName
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property streetNumber (base name: "street_number")', function() {
      // uncomment below and update the code to test the property streetNumber
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property apartment (base name: "apartment")', function() {
      // uncomment below and update the code to test the property apartment
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property neighborhood (base name: "neighborhood")', function() {
      // uncomment below and update the code to test the property neighborhood
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property policeArea (base name: "police_area")', function() {
      // uncomment below and update the code to test the property policeArea
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property zipCode (base name: "zip_code")', function() {
      // uncomment below and update the code to test the property zipCode
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property floor (base name: "floor")', function() {
      // uncomment below and update the code to test the property floor
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property neighborhoodParty (base name: "neighborhood_party")', function() {
      // uncomment below and update the code to test the property neighborhoodParty
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property block (base name: "block")', function() {
      // uncomment below and update the code to test the property block
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property allotment (base name: "allotment")', function() {
      // uncomment below and update the code to test the property allotment
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property observations (base name: "observations")', function() {
      // uncomment below and update the code to test the property observations
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property closeDate (base name: "close_date")', function() {
      // uncomment below and update the code to test the property closeDate
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses();
      //expect(instance).to.be();
    });

  });

}));
