/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NaranjaCustomerApiTesting);
  }
}(this, function(expect, NaranjaCustomerApiTesting) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NaranjaCustomerApiTesting.FilterrealId();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FilterrealId', function() {
    it('should create an instance of FilterrealId', function() {
      // uncomment below and update the code to test FilterrealId
      //var instance = new NaranjaCustomerApiTesting.FilterrealId();
      //expect(instance).to.be.a(NaranjaCustomerApiTesting.FilterrealId);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new NaranjaCustomerApiTesting.FilterrealId();
      //expect(instance).to.be();
    });

    it('should have the property accountId (base name: "account_id")', function() {
      // uncomment below and update the code to test the property accountId
      //var instance = new NaranjaCustomerApiTesting.FilterrealId();
      //expect(instance).to.be();
    });

    it('should have the property role (base name: "role")', function() {
      // uncomment below and update the code to test the property role
      //var instance = new NaranjaCustomerApiTesting.FilterrealId();
      //expect(instance).to.be();
    });

    it('should have the property personalDetails (base name: "personal_details")', function() {
      // uncomment below and update the code to test the property personalDetails
      //var instance = new NaranjaCustomerApiTesting.FilterrealId();
      //expect(instance).to.be();
    });

    it('should have the property birthDate (base name: "birth_date")', function() {
      // uncomment below and update the code to test the property birthDate
      //var instance = new NaranjaCustomerApiTesting.FilterrealId();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new NaranjaCustomerApiTesting.FilterrealId();
      //expect(instance).to.be();
    });

    it('should have the property conditions (base name: "conditions")', function() {
      // uncomment below and update the code to test the property conditions
      //var instance = new NaranjaCustomerApiTesting.FilterrealId();
      //expect(instance).to.be();
    });

    it('should have the property contactDetails (base name: "contact_details")', function() {
      // uncomment below and update the code to test the property contactDetails
      //var instance = new NaranjaCustomerApiTesting.FilterrealId();
      //expect(instance).to.be();
    });

  });

}));
