/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NaranjaCustomerApiTesting);
  }
}(this, function(expect, NaranjaCustomerApiTesting) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NaranjaCustomerApiTesting.FilterrealIdcontactdetailsaddresses();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FilterrealIdcontactdetailsaddresses', function() {
    it('should create an instance of FilterrealIdcontactdetailsaddresses', function() {
      // uncomment below and update the code to test FilterrealIdcontactdetailsaddresses
      //var instance = new NaranjaCustomerApiTesting.FilterrealIdcontactdetailsaddresses();
      //expect(instance).to.be.a(NaranjaCustomerApiTesting.FilterrealIdcontactdetailsaddresses);
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new NaranjaCustomerApiTesting.FilterrealIdcontactdetailsaddresses();
      //expect(instance).to.be();
    });

    it('should have the property fullAddress (base name: "full_address")', function() {
      // uncomment below and update the code to test the property fullAddress
      //var instance = new NaranjaCustomerApiTesting.FilterrealIdcontactdetailsaddresses();
      //expect(instance).to.be();
    });

    it('should have the property zipCode (base name: "zip_code")', function() {
      // uncomment below and update the code to test the property zipCode
      //var instance = new NaranjaCustomerApiTesting.FilterrealIdcontactdetailsaddresses();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new NaranjaCustomerApiTesting.FilterrealIdcontactdetailsaddresses();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new NaranjaCustomerApiTesting.FilterrealIdcontactdetailsaddresses();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new NaranjaCustomerApiTesting.FilterrealIdcontactdetailsaddresses();
      //expect(instance).to.be();
    });

  });

}));
