/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NaranjaCustomerApiTesting);
  }
}(this, function(expect, NaranjaCustomerApiTesting) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NaranjaCustomerApiTesting.Inlineresponse2002jobdetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Inlineresponse2002jobdetails', function() {
    it('should create an instance of Inlineresponse2002jobdetails', function() {
      // uncomment below and update the code to test Inlineresponse2002jobdetails
      //var instance = new NaranjaCustomerApiTesting.Inlineresponse2002jobdetails();
      //expect(instance).to.be.a(NaranjaCustomerApiTesting.Inlineresponse2002jobdetails);
    });

    it('should have the property activity (base name: "activity")', function() {
      // uncomment below and update the code to test the property activity
      //var instance = new NaranjaCustomerApiTesting.Inlineresponse2002jobdetails();
      //expect(instance).to.be();
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instance = new NaranjaCustomerApiTesting.Inlineresponse2002jobdetails();
      //expect(instance).to.be();
    });

    it('should have the property sector (base name: "sector")', function() {
      // uncomment below and update the code to test the property sector
      //var instance = new NaranjaCustomerApiTesting.Inlineresponse2002jobdetails();
      //expect(instance).to.be();
    });

    it('should have the property role (base name: "role")', function() {
      // uncomment below and update the code to test the property role
      //var instance = new NaranjaCustomerApiTesting.Inlineresponse2002jobdetails();
      //expect(instance).to.be();
    });

    it('should have the property dependency (base name: "dependency")', function() {
      // uncomment below and update the code to test the property dependency
      //var instance = new NaranjaCustomerApiTesting.Inlineresponse2002jobdetails();
      //expect(instance).to.be();
    });

    it('should have the property hired (base name: "hired")', function() {
      // uncomment below and update the code to test the property hired
      //var instance = new NaranjaCustomerApiTesting.Inlineresponse2002jobdetails();
      //expect(instance).to.be();
    });

    it('should have the property antiquity (base name: "antiquity")', function() {
      // uncomment below and update the code to test the property antiquity
      //var instance = new NaranjaCustomerApiTesting.Inlineresponse2002jobdetails();
      //expect(instance).to.be();
    });

    it('should have the property salary (base name: "salary")', function() {
      // uncomment below and update the code to test the property salary
      //var instance = new NaranjaCustomerApiTesting.Inlineresponse2002jobdetails();
      //expect(instance).to.be();
    });

  });

}));
