/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NaranjaCustomerApiTesting);
  }
}(this, function(expect, NaranjaCustomerApiTesting) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NaranjaCustomerApiTesting.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('apiHealthLivenessGet', function() {
      it('should call apiHealthLivenessGet successfully', function(done) {
        //uncomment below and update the code to test apiHealthLivenessGet
        //instance.apiHealthLivenessGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiHealthReadinessGet', function() {
      it('should call apiHealthReadinessGet successfully', function(done) {
        //uncomment below and update the code to test apiHealthReadinessGet
        //instance.apiHealthReadinessGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCustomerCbu', function() {
      it('should call deleteCustomerCbu successfully', function(done) {
        //uncomment below and update the code to test deleteCustomerCbu
        //instance.deleteCustomerCbu(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomer', function() {
      it('should call getCustomer successfully', function(done) {
        //uncomment below and update the code to test getCustomer
        //instance.getCustomer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomerAccount', function() {
      it('should call getCustomerAccount successfully', function(done) {
        //uncomment below and update the code to test getCustomerAccount
        //instance.getCustomerAccount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomerAddresses', function() {
      it('should call getCustomerAddresses successfully', function(done) {
        //uncomment below and update the code to test getCustomerAddresses
        //instance.getCustomerAddresses(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomerCbu', function() {
      it('should call getCustomerCbu successfully', function(done) {
        //uncomment below and update the code to test getCustomerCbu
        //instance.getCustomerCbu(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomerContactDetails', function() {
      it('should call getCustomerContactDetails successfully', function(done) {
        //uncomment below and update the code to test getCustomerContactDetails
        //instance.getCustomerContactDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomerEmail', function() {
      it('should call getCustomerEmail successfully', function(done) {
        //uncomment below and update the code to test getCustomerEmail
        //instance.getCustomerEmail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomerProducts', function() {
      it('should call getCustomerProducts successfully', function(done) {
        //uncomment below and update the code to test getCustomerProducts
        //instance.getCustomerProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomerPropensity', function() {
      it('should call getCustomerPropensity successfully', function(done) {
        //uncomment below and update the code to test getCustomerPropensity
        //instance.getCustomerPropensity(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFilter', function() {
      it('should call getFilter successfully', function(done) {
        //uncomment below and update the code to test getFilter
        //instance.getFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCustomerCbu', function() {
      it('should call postCustomerCbu successfully', function(done) {
        //uncomment below and update the code to test postCustomerCbu
        //instance.postCustomerCbu(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postValidateCbu', function() {
      it('should call postValidateCbu successfully', function(done) {
        //uncomment below and update the code to test postValidateCbu
        //instance.postValidateCbu(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCustomer', function() {
      it('should call putCustomer successfully', function(done) {
        //uncomment below and update the code to test putCustomer
        //instance.putCustomer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCustomerAddresses', function() {
      it('should call putCustomerAddresses successfully', function(done) {
        //uncomment below and update the code to test putCustomerAddresses
        //instance.putCustomerAddresses(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCustomerAdresses', function() {
      it('should call putCustomerAdresses successfully', function(done) {
        //uncomment below and update the code to test putCustomerAdresses
        //instance.putCustomerAdresses(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCustomerContactDetails', function() {
      it('should call putCustomerContactDetails successfully', function(done) {
        //uncomment below and update the code to test putCustomerContactDetails
        //instance.putCustomerContactDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCustomerEmail', function() {
      it('should call putCustomerEmail successfully', function(done) {
        //uncomment below and update the code to test putCustomerEmail
        //instance.putCustomerEmail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCustomerEmails', function() {
      it('should call putCustomerEmails successfully', function(done) {
        //uncomment below and update the code to test putCustomerEmails
        //instance.putCustomerEmails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCustomerPhone', function() {
      it('should call putCustomerPhone successfully', function(done) {
        //uncomment below and update the code to test putCustomerPhone
        //instance.putCustomerPhone(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('versionGet', function() {
      it('should call versionGet successfully', function(done) {
        //uncomment below and update the code to test versionGet
        //instance.versionGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
