/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Accountopenning = factory(root.NaranjaCustomerApiTesting.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Accountopenning model module.
   * @module model/Accountopenning
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Accountopenning</code>.
   * @alias module:model/Accountopenning
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Accountopenning</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Accountopenning} obj Optional instance to populate.
   * @return {module:model/Accountopenning} The populated <code>Accountopenning</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('risk_description')) {
        obj['risk_description'] = ApiClient.convertToType(data['risk_description'], 'String');
      }
      if (data.hasOwnProperty('brief_description')) {
        obj['brief_description'] = ApiClient.convertToType(data['brief_description'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} risk_description
   */
  exports.prototype['risk_description'] = undefined;
  /**
   * @member {String} brief_description
   */
  exports.prototype['brief_description'] = undefined;



  return exports;
}));


