/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Bodycustomerupdatejobdetails', 'model/Bodycustomerupdateowner', 'model/Bodycustomerupdatepersonaldetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Bodycustomerupdatejobdetails'), require('./Bodycustomerupdateowner'), require('./Bodycustomerupdatepersonaldetails'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Bodycustomerupdate = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Bodycustomerupdatejobdetails, root.NaranjaCustomerApiTesting.Bodycustomerupdateowner, root.NaranjaCustomerApiTesting.Bodycustomerupdatepersonaldetails);
  }
}(this, function(ApiClient, Bodycustomerupdatejobdetails, Bodycustomerupdateowner, Bodycustomerupdatepersonaldetails) {
  'use strict';



  /**
   * The Bodycustomerupdate model module.
   * @module model/Bodycustomerupdate
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Bodycustomerupdate</code>.
   * @alias module:model/Bodycustomerupdate
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Bodycustomerupdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Bodycustomerupdate} obj Optional instance to populate.
   * @return {module:model/Bodycustomerupdate} The populated <code>Bodycustomerupdate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
      if (data.hasOwnProperty('owner')) {
        obj['owner'] = Bodycustomerupdateowner.constructFromObject(data['owner']);
      }
      if (data.hasOwnProperty('personal_details')) {
        obj['personal_details'] = Bodycustomerupdatepersonaldetails.constructFromObject(data['personal_details']);
      }
      if (data.hasOwnProperty('job_details')) {
        obj['job_details'] = Bodycustomerupdatejobdetails.constructFromObject(data['job_details']);
      }
    }
    return obj;
  }

  /**
   * @member {String} role
   */
  exports.prototype['role'] = undefined;
  /**
   * @member {module:model/Bodycustomerupdateowner} owner
   */
  exports.prototype['owner'] = undefined;
  /**
   * @member {module:model/Bodycustomerupdatepersonaldetails} personal_details
   */
  exports.prototype['personal_details'] = undefined;
  /**
   * @member {module:model/Bodycustomerupdatejobdetails} job_details
   */
  exports.prototype['job_details'] = undefined;



  return exports;
}));


