/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Bodycustomerupdatejobdetailscompany', 'model/Bodycustomerupdatejobdetailssalary', 'model/Inlineresponse2002jobdetailsactivity'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Bodycustomerupdatejobdetailscompany'), require('./Bodycustomerupdatejobdetailssalary'), require('./Inlineresponse2002jobdetailsactivity'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Bodycustomerupdatejobdetails = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Bodycustomerupdatejobdetailscompany, root.NaranjaCustomerApiTesting.Bodycustomerupdatejobdetailssalary, root.NaranjaCustomerApiTesting.Inlineresponse2002jobdetailsactivity);
  }
}(this, function(ApiClient, Bodycustomerupdatejobdetailscompany, Bodycustomerupdatejobdetailssalary, Inlineresponse2002jobdetailsactivity) {
  'use strict';



  /**
   * The Bodycustomerupdatejobdetails model module.
   * @module model/Bodycustomerupdatejobdetails
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Bodycustomerupdatejobdetails</code>.
   * @alias module:model/Bodycustomerupdatejobdetails
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Bodycustomerupdatejobdetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Bodycustomerupdatejobdetails} obj Optional instance to populate.
   * @return {module:model/Bodycustomerupdatejobdetails} The populated <code>Bodycustomerupdatejobdetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('company')) {
        obj['company'] = Bodycustomerupdatejobdetailscompany.constructFromObject(data['company']);
      }
      if (data.hasOwnProperty('position')) {
        obj['position'] = Inlineresponse2002jobdetailsactivity.constructFromObject(data['position']);
      }
      if (data.hasOwnProperty('is_employed')) {
        obj['is_employed'] = ApiClient.convertToType(data['is_employed'], 'Boolean');
      }
      if (data.hasOwnProperty('labor_seniority')) {
        obj['labor_seniority'] = ApiClient.convertToType(data['labor_seniority'], 'Number');
      }
      if (data.hasOwnProperty('salary')) {
        obj['salary'] = Bodycustomerupdatejobdetailssalary.constructFromObject(data['salary']);
      }
      if (data.hasOwnProperty('has_own_house')) {
        obj['has_own_house'] = ApiClient.convertToType(data['has_own_house'], 'Boolean');
      }
      if (data.hasOwnProperty('has_own_car')) {
        obj['has_own_car'] = ApiClient.convertToType(data['has_own_car'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Bodycustomerupdatejobdetailscompany} company
   */
  exports.prototype['company'] = undefined;
  /**
   * @member {module:model/Inlineresponse2002jobdetailsactivity} position
   */
  exports.prototype['position'] = undefined;
  /**
   * @member {Boolean} is_employed
   */
  exports.prototype['is_employed'] = undefined;
  /**
   * @member {Number} labor_seniority
   */
  exports.prototype['labor_seniority'] = undefined;
  /**
   * @member {module:model/Bodycustomerupdatejobdetailssalary} salary
   */
  exports.prototype['salary'] = undefined;
  /**
   * @member {Boolean} has_own_house
   */
  exports.prototype['has_own_house'] = undefined;
  /**
   * @member {Boolean} has_own_car
   */
  exports.prototype['has_own_car'] = undefined;



  return exports;
}));


