/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Inlineresponse2002jobdetailsactivity'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Inlineresponse2002jobdetailsactivity'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Bodycustomerupdatejobdetailscompany = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Inlineresponse2002jobdetailsactivity);
  }
}(this, function(ApiClient, Inlineresponse2002jobdetailsactivity) {
  'use strict';



  /**
   * The Bodycustomerupdatejobdetailscompany model module.
   * @module model/Bodycustomerupdatejobdetailscompany
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Bodycustomerupdatejobdetailscompany</code>.
   * @alias module:model/Bodycustomerupdatejobdetailscompany
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Bodycustomerupdatejobdetailscompany</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Bodycustomerupdatejobdetailscompany} obj Optional instance to populate.
   * @return {module:model/Bodycustomerupdatejobdetailscompany} The populated <code>Bodycustomerupdatejobdetailscompany</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = Inlineresponse2002jobdetailsactivity.constructFromObject(data['type']);
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/Inlineresponse2002jobdetailsactivity} type
   */
  exports.prototype['type'] = undefined;



  return exports;
}));


