/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Account', 'model/Contactdetails', 'model/Jobdetails', 'model/Limits', 'model/Personaldetails2'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Account'), require('./Contactdetails'), require('./Jobdetails'), require('./Limits'), require('./Personaldetails2'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Customer = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Account, root.NaranjaCustomerApiTesting.Contactdetails, root.NaranjaCustomerApiTesting.Jobdetails, root.NaranjaCustomerApiTesting.Limits, root.NaranjaCustomerApiTesting.Personaldetails2);
  }
}(this, function(ApiClient, Account, Contactdetails, Jobdetails, Limits, Personaldetails2) {
  'use strict';



  /**
   * The Customer model module.
   * @module model/Customer
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Customer</code>.
   * @alias module:model/Customer
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Customer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Customer} obj Optional instance to populate.
   * @return {module:model/Customer} The populated <code>Customer</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
      if (data.hasOwnProperty('account')) {
        obj['account'] = Account.constructFromObject(data['account']);
      }
      if (data.hasOwnProperty('personal_details')) {
        obj['personal_details'] = Personaldetails2.constructFromObject(data['personal_details']);
      }
      if (data.hasOwnProperty('contact_details')) {
        obj['contact_details'] = Contactdetails.constructFromObject(data['contact_details']);
      }
      if (data.hasOwnProperty('job_details')) {
        obj['job_details'] = Jobdetails.constructFromObject(data['job_details']);
      }
      if (data.hasOwnProperty('limits')) {
        obj['limits'] = Limits.constructFromObject(data['limits']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} role
   */
  exports.prototype['role'] = undefined;
  /**
   * @member {module:model/Account} account
   */
  exports.prototype['account'] = undefined;
  /**
   * @member {module:model/Personaldetails2} personal_details
   */
  exports.prototype['personal_details'] = undefined;
  /**
   * @member {module:model/Contactdetails} contact_details
   */
  exports.prototype['contact_details'] = undefined;
  /**
   * @member {module:model/Jobdetails} job_details
   */
  exports.prototype['job_details'] = undefined;
  /**
   * @member {module:model/Limits} limits
   */
  exports.prototype['limits'] = undefined;



  return exports;
}));


