/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Customerscustomeridcontactdetailsaddressescategoryidcity', 'model/Customerscustomeridcontactdetailsaddressescategoryidcountry', 'model/Customerscustomeridcontactdetailsaddressescategoryidstate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Customerscustomeridcontactdetailsaddressescategoryidcity'), require('./Customerscustomeridcontactdetailsaddressescategoryidcountry'), require('./Customerscustomeridcontactdetailsaddressescategoryidstate'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidaddresses = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidcity, root.NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidcountry, root.NaranjaCustomerApiTesting.Customerscustomeridcontactdetailsaddressescategoryidstate);
  }
}(this, function(ApiClient, Customerscustomeridcontactdetailsaddressescategoryidcity, Customerscustomeridcontactdetailsaddressescategoryidcountry, Customerscustomeridcontactdetailsaddressescategoryidstate) {
  'use strict';



  /**
   * The Customerscustomeridcontactdetailsaddressescategoryidaddresses model module.
   * @module model/Customerscustomeridcontactdetailsaddressescategoryidaddresses
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Customerscustomeridcontactdetailsaddressescategoryidaddresses</code>.
   * @alias module:model/Customerscustomeridcontactdetailsaddressescategoryidaddresses
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Customerscustomeridcontactdetailsaddressescategoryidaddresses</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Customerscustomeridcontactdetailsaddressescategoryidaddresses} obj Optional instance to populate.
   * @return {module:model/Customerscustomeridcontactdetailsaddressescategoryidaddresses} The populated <code>Customerscustomeridcontactdetailsaddressescategoryidaddresses</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('street_name')) {
        obj['street_name'] = ApiClient.convertToType(data['street_name'], 'String');
      }
      if (data.hasOwnProperty('street_number')) {
        obj['street_number'] = ApiClient.convertToType(data['street_number'], 'Number');
      }
      if (data.hasOwnProperty('apartment')) {
        obj['apartment'] = ApiClient.convertToType(data['apartment'], 'String');
      }
      if (data.hasOwnProperty('neighborhood')) {
        obj['neighborhood'] = ApiClient.convertToType(data['neighborhood'], 'String');
      }
      if (data.hasOwnProperty('police_area')) {
        obj['police_area'] = ApiClient.convertToType(data['police_area'], 'Number');
      }
      if (data.hasOwnProperty('zip_code')) {
        obj['zip_code'] = ApiClient.convertToType(data['zip_code'], 'Number');
      }
      if (data.hasOwnProperty('floor')) {
        obj['floor'] = ApiClient.convertToType(data['floor'], 'String');
      }
      if (data.hasOwnProperty('neighborhood_party')) {
        obj['neighborhood_party'] = ApiClient.convertToType(data['neighborhood_party'], 'String');
      }
      if (data.hasOwnProperty('block')) {
        obj['block'] = ApiClient.convertToType(data['block'], 'String');
      }
      if (data.hasOwnProperty('allotment')) {
        obj['allotment'] = ApiClient.convertToType(data['allotment'], 'String');
      }
      if (data.hasOwnProperty('observations')) {
        obj['observations'] = ApiClient.convertToType(data['observations'], 'String');
      }
      if (data.hasOwnProperty('close_date')) {
        obj['close_date'] = ApiClient.convertToType(data['close_date'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = Customerscustomeridcontactdetailsaddressescategoryidcity.constructFromObject(data['city']);
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = Customerscustomeridcontactdetailsaddressescategoryidstate.constructFromObject(data['state']);
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = Customerscustomeridcontactdetailsaddressescategoryidcountry.constructFromObject(data['country']);
      }
    }
    return obj;
  }

  /**
   * @member {String} street_name
   */
  exports.prototype['street_name'] = undefined;
  /**
   * @member {Number} street_number
   */
  exports.prototype['street_number'] = undefined;
  /**
   * @member {String} apartment
   */
  exports.prototype['apartment'] = undefined;
  /**
   * @member {String} neighborhood
   */
  exports.prototype['neighborhood'] = undefined;
  /**
   * @member {Number} police_area
   */
  exports.prototype['police_area'] = undefined;
  /**
   * @member {Number} zip_code
   */
  exports.prototype['zip_code'] = undefined;
  /**
   * @member {String} floor
   */
  exports.prototype['floor'] = undefined;
  /**
   * @member {String} neighborhood_party
   */
  exports.prototype['neighborhood_party'] = undefined;
  /**
   * @member {String} block
   */
  exports.prototype['block'] = undefined;
  /**
   * @member {String} allotment
   */
  exports.prototype['allotment'] = undefined;
  /**
   * @member {String} observations
   */
  exports.prototype['observations'] = undefined;
  /**
   * @member {String} close_date
   */
  exports.prototype['close_date'] = undefined;
  /**
   * @member {module:model/Customerscustomeridcontactdetailsaddressescategoryidcity} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {module:model/Customerscustomeridcontactdetailsaddressescategoryidstate} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {module:model/Customerscustomeridcontactdetailsaddressescategoryidcountry} country
   */
  exports.prototype['country'] = undefined;



  return exports;
}));


