/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FilterrealIdconditions', 'model/FilterrealIdcontactdetails', 'model/FilterrealIdpersonaldetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FilterrealIdconditions'), require('./FilterrealIdcontactdetails'), require('./FilterrealIdpersonaldetails'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.FilterrealId = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.FilterrealIdconditions, root.NaranjaCustomerApiTesting.FilterrealIdcontactdetails, root.NaranjaCustomerApiTesting.FilterrealIdpersonaldetails);
  }
}(this, function(ApiClient, FilterrealIdconditions, FilterrealIdcontactdetails, FilterrealIdpersonaldetails) {
  'use strict';



  /**
   * The FilterrealId model module.
   * @module model/FilterrealId
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>FilterrealId</code>.
   * @alias module:model/FilterrealId
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>FilterrealId</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FilterrealId} obj Optional instance to populate.
   * @return {module:model/FilterrealId} The populated <code>FilterrealId</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('account_id')) {
        obj['account_id'] = ApiClient.convertToType(data['account_id'], 'String');
      }
      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
      if (data.hasOwnProperty('personal_details')) {
        obj['personal_details'] = FilterrealIdpersonaldetails.constructFromObject(data['personal_details']);
      }
      if (data.hasOwnProperty('birth_date')) {
        obj['birth_date'] = ApiClient.convertToType(data['birth_date'], 'String');
      }
      if (data.hasOwnProperty('gender')) {
        obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
      }
      if (data.hasOwnProperty('conditions')) {
        obj['conditions'] = FilterrealIdconditions.constructFromObject(data['conditions']);
      }
      if (data.hasOwnProperty('contact_details')) {
        obj['contact_details'] = FilterrealIdcontactdetails.constructFromObject(data['contact_details']);
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} account_id
   */
  exports.prototype['account_id'] = undefined;
  /**
   * @member {String} role
   */
  exports.prototype['role'] = undefined;
  /**
   * @member {module:model/FilterrealIdpersonaldetails} personal_details
   */
  exports.prototype['personal_details'] = undefined;
  /**
   * @member {String} birth_date
   */
  exports.prototype['birth_date'] = undefined;
  /**
   * @member {String} gender
   */
  exports.prototype['gender'] = undefined;
  /**
   * @member {module:model/FilterrealIdconditions} conditions
   */
  exports.prototype['conditions'] = undefined;
  /**
   * @member {module:model/FilterrealIdcontactdetails} contact_details
   */
  exports.prototype['contact_details'] = undefined;



  return exports;
}));


