/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Cbuentity'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Cbuentity'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Getcbu200 = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Cbuentity);
  }
}(this, function(ApiClient, Cbuentity) {
  'use strict';



  /**
   * The Getcbu200 model module.
   * @module model/Getcbu200
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Getcbu200</code>.
   * @alias module:model/Getcbu200
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Getcbu200</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Getcbu200} obj Optional instance to populate.
   * @return {module:model/Getcbu200} The populated <code>Getcbu200</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('cbus')) {
        obj['cbus'] = ApiClient.convertToType(data['cbus'], [Cbuentity]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Cbuentity>} cbus
   */
  exports.prototype['cbus'] = undefined;



  return exports;
}));


