/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Propensities'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Propensities'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Inlineresponse200 = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Propensities);
  }
}(this, function(ApiClient, Propensities) {
  'use strict';



  /**
   * The Inlineresponse200 model module.
   * @module model/Inlineresponse200
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Inlineresponse200</code>.
   * @alias module:model/Inlineresponse200
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Inlineresponse200</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Inlineresponse200} obj Optional instance to populate.
   * @return {module:model/Inlineresponse200} The populated <code>Inlineresponse200</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('propensities')) {
        obj['propensities'] = ApiClient.convertToType(data['propensities'], [Propensities]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Propensities>} propensities
   */
  exports.prototype['propensities'] = undefined;



  return exports;
}));


