/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Inlineresponse2006lastupdateemails', 'model/Inlineresponse2006lastupdatephones'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Inlineresponse2006lastupdateemails'), require('./Inlineresponse2006lastupdatephones'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Inlineresponse2006lastupdate = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Inlineresponse2006lastupdateemails, root.NaranjaCustomerApiTesting.Inlineresponse2006lastupdatephones);
  }
}(this, function(ApiClient, Inlineresponse2006lastupdateemails, Inlineresponse2006lastupdatephones) {
  'use strict';



  /**
   * The Inlineresponse2006lastupdate model module.
   * @module model/Inlineresponse2006lastupdate
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Inlineresponse2006lastupdate</code>.
   * @alias module:model/Inlineresponse2006lastupdate
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Inlineresponse2006lastupdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Inlineresponse2006lastupdate} obj Optional instance to populate.
   * @return {module:model/Inlineresponse2006lastupdate} The populated <code>Inlineresponse2006lastupdate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('phones')) {
        obj['phones'] = Inlineresponse2006lastupdatephones.constructFromObject(data['phones']);
      }
      if (data.hasOwnProperty('emails')) {
        obj['emails'] = Inlineresponse2006lastupdateemails.constructFromObject(data['emails']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Inlineresponse2006lastupdatephones} phones
   */
  exports.prototype['phones'] = undefined;
  /**
   * @member {module:model/Inlineresponse2006lastupdateemails} emails
   */
  exports.prototype['emails'] = undefined;



  return exports;
}));


