/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Inlineresponse2004error', 'model/Inlineresponse2004success'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Inlineresponse2004error'), require('./Inlineresponse2004success'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Inlineresponse2004 = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Inlineresponse2004error, root.NaranjaCustomerApiTesting.Inlineresponse2004success);
  }
}(this, function(ApiClient, Inlineresponse2004error, Inlineresponse2004success) {
  'use strict';



  /**
   * The Inlineresponse2004 model module.
   * @module model/Inlineresponse2004
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Inlineresponse2004</code>.
   * @alias module:model/Inlineresponse2004
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Inlineresponse2004</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Inlineresponse2004} obj Optional instance to populate.
   * @return {module:model/Inlineresponse2004} The populated <code>Inlineresponse2004</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('success')) {
        obj['success'] = ApiClient.convertToType(data['success'], [Inlineresponse2004success]);
      }
      if (data.hasOwnProperty('error')) {
        obj['error'] = ApiClient.convertToType(data['error'], [Inlineresponse2004error]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Inlineresponse2004success>} success
   */
  exports.prototype['success'] = undefined;
  /**
   * @member {Array.<module:model/Inlineresponse2004error>} error
   */
  exports.prototype['error'] = undefined;



  return exports;
}));


