/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Inlineresponse2002jobdetailsactivity', 'model/Inlineresponse2002jobdetailsrole', 'model/Inlineresponse2002jobdetailssector'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Inlineresponse2002jobdetailsactivity'), require('./Inlineresponse2002jobdetailsrole'), require('./Inlineresponse2002jobdetailssector'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Inlineresponse2002jobdetails = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Inlineresponse2002jobdetailsactivity, root.NaranjaCustomerApiTesting.Inlineresponse2002jobdetailsrole, root.NaranjaCustomerApiTesting.Inlineresponse2002jobdetailssector);
  }
}(this, function(ApiClient, Inlineresponse2002jobdetailsactivity, Inlineresponse2002jobdetailsrole, Inlineresponse2002jobdetailssector) {
  'use strict';



  /**
   * The Inlineresponse2002jobdetails model module.
   * @module model/Inlineresponse2002jobdetails
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Inlineresponse2002jobdetails</code>.
   * @alias module:model/Inlineresponse2002jobdetails
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Inlineresponse2002jobdetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Inlineresponse2002jobdetails} obj Optional instance to populate.
   * @return {module:model/Inlineresponse2002jobdetails} The populated <code>Inlineresponse2002jobdetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('activity')) {
        obj['activity'] = Inlineresponse2002jobdetailsactivity.constructFromObject(data['activity']);
      }
      if (data.hasOwnProperty('company')) {
        obj['company'] = ApiClient.convertToType(data['company'], 'String');
      }
      if (data.hasOwnProperty('sector')) {
        obj['sector'] = Inlineresponse2002jobdetailssector.constructFromObject(data['sector']);
      }
      if (data.hasOwnProperty('role')) {
        obj['role'] = Inlineresponse2002jobdetailsrole.constructFromObject(data['role']);
      }
      if (data.hasOwnProperty('dependency')) {
        obj['dependency'] = ApiClient.convertToType(data['dependency'], 'Boolean');
      }
      if (data.hasOwnProperty('hired')) {
        obj['hired'] = ApiClient.convertToType(data['hired'], 'Boolean');
      }
      if (data.hasOwnProperty('antiquity')) {
        obj['antiquity'] = ApiClient.convertToType(data['antiquity'], 'Number');
      }
      if (data.hasOwnProperty('salary')) {
        obj['salary'] = ApiClient.convertToType(data['salary'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Inlineresponse2002jobdetailsactivity} activity
   */
  exports.prototype['activity'] = undefined;
  /**
   * @member {String} company
   */
  exports.prototype['company'] = undefined;
  /**
   * @member {module:model/Inlineresponse2002jobdetailssector} sector
   */
  exports.prototype['sector'] = undefined;
  /**
   * @member {module:model/Inlineresponse2002jobdetailsrole} role
   */
  exports.prototype['role'] = undefined;
  /**
   * @member {Boolean} dependency
   */
  exports.prototype['dependency'] = undefined;
  /**
   * @member {Boolean} hired
   */
  exports.prototype['hired'] = undefined;
  /**
   * @member {Number} antiquity
   */
  exports.prototype['antiquity'] = undefined;
  /**
   * @member {Number} salary
   */
  exports.prototype['salary'] = undefined;



  return exports;
}));


