/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Inlineresponse2004result'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Inlineresponse2004result'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Inlineresponse2004success = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Inlineresponse2004result);
  }
}(this, function(ApiClient, Inlineresponse2004result) {
  'use strict';



  /**
   * The Inlineresponse2004success model module.
   * @module model/Inlineresponse2004success
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Inlineresponse2004success</code>.
   * @alias module:model/Inlineresponse2004success
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Inlineresponse2004success</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Inlineresponse2004success} obj Optional instance to populate.
   * @return {module:model/Inlineresponse2004success} The populated <code>Inlineresponse2004success</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('category')) {
        obj['category'] = ApiClient.convertToType(data['category'], 'String');
      }
      if (data.hasOwnProperty('result')) {
        obj['result'] = Inlineresponse2004result.constructFromObject(data['result']);
      }
    }
    return obj;
  }

  /**
   * @member {String} category
   */
  exports.prototype['category'] = undefined;
  /**
   * @member {module:model/Inlineresponse2004result} result
   */
  exports.prototype['result'] = undefined;



  return exports;
}));


