/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Inlineresponse2002jobdetails', 'model/Inlineresponse2002ownercontactdetails', 'model/Personaldetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Inlineresponse2002jobdetails'), require('./Inlineresponse2002ownercontactdetails'), require('./Personaldetails'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Inlineresponse2002guarantors = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Inlineresponse2002jobdetails, root.NaranjaCustomerApiTesting.Inlineresponse2002ownercontactdetails, root.NaranjaCustomerApiTesting.Personaldetails);
  }
}(this, function(ApiClient, Inlineresponse2002jobdetails, Inlineresponse2002ownercontactdetails, Personaldetails) {
  'use strict';



  /**
   * The Inlineresponse2002guarantors model module.
   * @module model/Inlineresponse2002guarantors
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Inlineresponse2002guarantors</code>.
   * @alias module:model/Inlineresponse2002guarantors
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Inlineresponse2002guarantors</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Inlineresponse2002guarantors} obj Optional instance to populate.
   * @return {module:model/Inlineresponse2002guarantors} The populated <code>Inlineresponse2002guarantors</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('personal_details')) {
        obj['personal_details'] = Personaldetails.constructFromObject(data['personal_details']);
      }
      if (data.hasOwnProperty('contact_details')) {
        obj['contact_details'] = Inlineresponse2002ownercontactdetails.constructFromObject(data['contact_details']);
      }
      if (data.hasOwnProperty('job_details')) {
        obj['job_details'] = Inlineresponse2002jobdetails.constructFromObject(data['job_details']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/Personaldetails} personal_details
   */
  exports.prototype['personal_details'] = undefined;
  /**
   * @member {module:model/Inlineresponse2002ownercontactdetails} contact_details
   */
  exports.prototype['contact_details'] = undefined;
  /**
   * @member {module:model/Inlineresponse2002jobdetails} job_details
   */
  exports.prototype['job_details'] = undefined;



  return exports;
}));


