/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Inlineresponse2002ownercontactdetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Inlineresponse2002ownercontactdetails'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Inputcontactdetails = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Inlineresponse2002ownercontactdetails);
  }
}(this, function(ApiClient, Inlineresponse2002ownercontactdetails) {
  'use strict';



  /**
   * The Inputcontactdetails model module.
   * @module model/Inputcontactdetails
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Inputcontactdetails</code>.
   * @alias module:model/Inputcontactdetails
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Inputcontactdetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Inputcontactdetails} obj Optional instance to populate.
   * @return {module:model/Inputcontactdetails} The populated <code>Inputcontactdetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('contact_details')) {
        obj['contact_details'] = Inlineresponse2002ownercontactdetails.constructFromObject(data['contact_details']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Inlineresponse2002ownercontactdetails} contact_details
   */
  exports.prototype['contact_details'] = undefined;



  return exports;
}));


