/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Limits = factory(root.NaranjaCustomerApiTesting.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Limits model module.
   * @module model/Limits
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Limits</code>.
   * @alias module:model/Limits
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Limits</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Limits} obj Optional instance to populate.
   * @return {module:model/Limits} The populated <code>Limits</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('monthly')) {
        obj['monthly'] = ApiClient.convertToType(data['monthly'], 'Number');
      }
      if (data.hasOwnProperty('zeta')) {
        obj['zeta'] = ApiClient.convertToType(data['zeta'], 'Number');
      }
      if (data.hasOwnProperty('cpl')) {
        obj['cpl'] = ApiClient.convertToType(data['cpl'], 'Number');
      }
      if (data.hasOwnProperty('etp')) {
        obj['etp'] = ApiClient.convertToType(data['etp'], 'Number');
      }
      if (data.hasOwnProperty('cplom')) {
        obj['cplom'] = ApiClient.convertToType(data['cplom'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} monthly
   */
  exports.prototype['monthly'] = undefined;
  /**
   * @member {Number} zeta
   */
  exports.prototype['zeta'] = undefined;
  /**
   * @member {Number} cpl
   */
  exports.prototype['cpl'] = undefined;
  /**
   * @member {Number} etp
   */
  exports.prototype['etp'] = undefined;
  /**
   * @member {Number} cplom
   */
  exports.prototype['cplom'] = undefined;



  return exports;
}));


