/**
 * naranja-customer-api-testing
 * sarasa
 *
 * The version of the OpenAPI document: 3.2.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Postcbuvalidate200accountbankownerfiscaldata'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Postcbuvalidate200accountbankownerfiscaldata'));
  } else {
    // Browser globals (root is window)
    if (!root.NaranjaCustomerApiTesting) {
      root.NaranjaCustomerApiTesting = {};
    }
    root.NaranjaCustomerApiTesting.Postcbuvalidate200accountbankowner = factory(root.NaranjaCustomerApiTesting.ApiClient, root.NaranjaCustomerApiTesting.Postcbuvalidate200accountbankownerfiscaldata);
  }
}(this, function(ApiClient, Postcbuvalidate200accountbankownerfiscaldata) {
  'use strict';



  /**
   * The Postcbuvalidate200accountbankowner model module.
   * @module model/Postcbuvalidate200accountbankowner
   * @version 3.2.1
   */

  /**
   * Constructs a new <code>Postcbuvalidate200accountbankowner</code>.
   * @alias module:model/Postcbuvalidate200accountbankowner
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Postcbuvalidate200accountbankowner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Postcbuvalidate200accountbankowner} obj Optional instance to populate.
   * @return {module:model/Postcbuvalidate200accountbankowner} The populated <code>Postcbuvalidate200accountbankowner</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('fiscal_data')) {
        obj['fiscal_data'] = Postcbuvalidate200accountbankownerfiscaldata.constructFromObject(data['fiscal_data']);
      }
      if (data.hasOwnProperty('full_name')) {
        obj['full_name'] = ApiClient.convertToType(data['full_name'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {module:model/Postcbuvalidate200accountbankownerfiscaldata} fiscal_data
   */
  exports.prototype['fiscal_data'] = undefined;
  /**
   * @member {String} full_name
   */
  exports.prototype['full_name'] = undefined;



  return exports;
}));


